language: python
python:
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install pipenv
  - pipenv install
  - pipenv install codeclimate-test-reporter
# command to run tests
script:
  - py.test --cov=check_docker
  - codeclimate-test-reporter || echo "Ignoring Code Climate reporter upload failure"
